name: Deploy to samsclub

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Build Astro website
      run: npm run build
      
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.PI_USERNAME }}
        key: ${{ secrets.PI_SSH_KEY }}
        script: |
          docker pull docker.pkg.github.com/samperlmutter/samperlmutter.dev:latest
          docker stop astro-website
          docker run -d --name astro-website -p 80:80 ghcr.io/${{ github.repository }}:${{ github.ref_name }}